spring:
  application:
    name: healtheng_auth
  datasource:
    jpa:
      jdbc-url: ${POSTGRESQL_URI:jdbc:postgresql://localhost:5432/health_auth}
      username: sa
      password: 1
      driver-class-name: org.postgresql.Driver
#  datasource:
#    jpa:
#      url: jdbc:postgresql://localhost:5432/health_auth
#      username: sa
#      password: 1
#      driver-class-name: org.postgresql.Driver

